import org.jetbrains.intellij.platform.gradle.TestFrameworkType

plugins {
    id 'java'
    id 'org.jetbrains.intellij.platform' version '2.5.0'
}

group = 'org.jankos'
version = '1.0-SNAPSHOT'

repositories {
    mavenCentral()
    gradlePluginPortal()
    intellijPlatform {
        defaultRepositories()
    }
}

dependencies {

    // Required dependencies
    implementation("org.freemarker:freemarker:2.3.31")
    implementation "org.jetbrains:annotations:24.0.1"
    compileOnly 'org.projectlombok:lombok:1.18.24'
    annotationProcessor 'org.projectlombok:lombok:1.18.24'

    // Test dependencies
    testImplementation platform('org.junit:junit-bom:5.10.0')
    testImplementation 'org.junit.jupiter:junit-jupiter'
    testImplementation 'org.mockito:mockito-core:4.8.0'
    testImplementation 'org.assertj:assertj-core:3.24.2'

    intellijPlatform {
        intellijIdeaUltimate('2024.2.4')
        testFramework TestFrameworkType.Platform.INSTANCE
        bundledPlugin 'com.intellij.java'
    }
}

sourceSets {
    main {
        resources {
            srcDir 'src/main/resources'
        }
    }
}

tasks {
    patchPluginXml {
        changeNotes = """
            Initial plugin setup.
        """
    }

    test {
        useJUnitPlatform()
    }
}

tasks.named('processResources') {
    duplicatesStrategy = DuplicatesStrategy.EXCLUDE
}

patchPluginXml {
    sinceBuild = '232'  // IntelliJ 2023.2
    untilBuild = '242.*' // IntelliJ 2024.2+
}

runIde {
    jvmArgs = ['-Xmx2g']
}

signPlugin {
    certificateChain = System.getenv('CERTIFICATE_CHAIN')
    privateKey = System.getenv('PRIVATE_KEY')
    password = System.getenv('PRIVATE_KEY_PASSWORD')
}

publishPlugin {
    token = System.getenv('PUBLISH_TOKEN')
}

tasks.register("downloadDocs") {
    doLast {
        configurations.compileClasspath.resolvedConfiguration.resolvedArtifacts.each { artifact ->
            println "Downloading docs for: ${artifact.moduleVersion.id}"
            try {
                artifact.moduleVersion.id.componentIdentifier.artifactName
                def sources = dependencies.create("${artifact.moduleVersion.id}@sources")
                def javadoc = dependencies.create("${artifact.moduleVersion.id}@javadoc")
                configurations.detachedConfiguration(sources, javadoc).resolve()
            } catch (Exception e) {
                println "Unable to download docs for ${artifact.moduleVersion.id}: ${e.message}"
            }
        }
    }
}